/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letsevent;

import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

public class FramePendaftarann extends javax.swing.JFrame {

    private String idPassEvent;
    public boolean databaru;
    private Connection con;
    private PreparedStatement ps;
    private Statement st;
    private ResultSet rs;
    
    public FramePendaftarann() {
        initComponents();
        getData();
        databaru = true;
        // Mendapatkan tanggal hari ini
        LocalDate today = LocalDate.now();

        // Mengonversi LocalDate menjadi Date
        Date date = java.sql.Date.valueOf(today);

        // Mengatur tanggal saat ini pada JDateChooser
        txtDate.setDate(date);
    }

    public void setIdEvent(String idEvent) {
        this.idPassEvent = idEvent;
                
        // Isi nilai ID ke textfield
        txtIdEvent.setText(String.valueOf(idEvent));
    }
        
    //mengambil data 
    private void getData()
    {
        // menampilkan data dari database
        try 
        {
            DefaultTableModel model = new DefaultTableModel();         
            con = (Connection) Koneksi.getKoneksi();
            st = con.createStatement();
            rs = st.executeQuery("SELECT id_pendaftaran AS ID, nama_peserta AS 'Name', no_telp AS 'Phone Number', email AS 'Email', tanggal_pendaftaran AS 'Registration Date' FROM pendaftaran WHERE id_event ='"+txtIdEvent.getText()+"'");
            tblPendaftaran.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException | HeadlessException e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public void getDataMasuk()
    {
        // menampilkan data dari database
        try 
        {
            DefaultTableModel model = new DefaultTableModel();         
            con = (Connection) Koneksi.getKoneksi();
            st = con.createStatement();
            rs = st.executeQuery("SELECT id_pendaftaran AS ID, nama_peserta AS 'Name', no_telp AS 'Phone Number', email AS 'Email', tanggal_pendaftaran AS 'Registration Date' FROM pendaftaran WHERE id_event ='"+txtIdEvent.getText()+"'");
            tblPendaftaran.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException | HeadlessException e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void cleanData(){
        // mengosongkan textbox
        txtId.setText("");
        txtPhone.setText("");
        txtNama.setText("");
        txtEmail.setText("");
    }
    /**

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtCari = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendaftaran = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdEvent = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 236, 399, 29));

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 278, 399, 29));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 399, 30));

        txtDate.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 363, 399, 28));
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 176, 28));

        btnTambah.setText("Add");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 89, 29));

        btnSimpan.setText("Save/Update");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 410, 91, 30));

        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 410, 89, 29));

        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 411, 89, 29));

        btnCari.setText("Search");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 459, 89, 29));

        tblPendaftaran.setBackground(new java.awt.Color(119, 172, 229));
        tblPendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Name", "Phone Number", "Email", "Registration Date"
            }
        ));
        tblPendaftaran.setRowHeight(24);
        tblPendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendaftaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPendaftaran);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 510, 858, 164));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letsevent/icon _arrow left circled_.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letsevent/Tabel Pendaftaran.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));
        getContentPane().add(txtIdEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Input harus berupa nomor.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        String allowedChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@._";
        char typedChar = evt.getKeyChar();

        if (typedChar != KeyEvent.VK_BACK_SPACE  && (txtEmail.getText().length() >= 50 || !allowedChars.contains(String.valueOf(typedChar)))) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Input harus berupa email yang valid.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        databaru=true;
        cleanData();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String idPendaftaran = txtId.getText();
        String namaPeserta = txtNama.getText();
        String email = txtEmail.getText();
        // Mengambil tanggal dari JDateChooser
        Date tanggalPendaftaran = txtDate.getDate();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String strTanggal = format.format(tanggalPendaftaran); // memformat tanggal menjadi string

        String nomorTelepon = txtPhone.getText();
        String idEvent = txtIdEvent.getText();

        if (databaru == true) { // prosess simpan atau edit
            try
            {
                String sql = "INSERT INTO pendaftaran(nama_peserta, no_telp, email, tanggal_pendaftaran, id_event) VALUES (?, ?, ?, ?, ?)";
                con = (Connection) Koneksi.getKoneksi();
                ps = con.prepareStatement(sql);
                ps.setString(1, namaPeserta);
                ps.setString(2, nomorTelepon);
                ps.setString(3, email);
                ps.setString(4, strTanggal);
                ps.setString(5, idEvent);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil didaftarkan");
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        else {
            try
            {
                String sql = "UPDATE pendaftaran SET nama_peserta=?, no_telp=?, email=?,tanggal_pendaftaran=? WHERE id_pendaftaran=?";
                con = (Connection) Koneksi.getKoneksi();
                ps = con.prepareStatement(sql);
                ps.setString(1, namaPeserta);
                ps.setString(2, nomorTelepon);
                ps.setString(3, email);
                ps.setString(4, strTanggal);
                ps.setString(5, idPendaftaran);
                ps.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        cleanData();
        getData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            String id = txtId.getText();
            con = (Connection) Koneksi.getKoneksi();

            int option = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data? Data tiket yang sudah dipesan juga akan terhapus.", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                // Hapus data terkait dari tabel anak (tiket)
                String deleteTiketSql = "DELETE FROM tiket WHERE id_pendaftaran = ?";
                ps = con.prepareStatement(deleteTiketSql);
                ps.setString(1, id);
                ps.executeUpdate();

                // Hapus data dari tabel induk (pendaftaran)
                String deletePendaftaranSql = "DELETE FROM pendaftaran WHERE id_pendaftaran = ?";
                ps = con.prepareStatement(deletePendaftaranSql);
                ps.setString(1, id);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Berhasil Dihapus");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        cleanData();
        getData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        // Ambil nilai ID yang ingin Anda lewatkan
        String idPassEvent2 = txtIdEvent.getText();
        String idPassPendaftaran = txtId.getText();

        // sembunyikan frame pendaftaram
        this.setVisible(false);

        // Buat instance dari frame Tiket
        FrameTikett frameTikett = new FrameTikett();

        // Panggil method di frame B untuk mengatur nilai ID
        frameTikett.setIdEvent(idPassEvent2);

        // Panggil method di frame tiket untuk mengatur nilai ID pendaftaran
        frameTikett.setIdPendaftaran(idPassPendaftaran);

        frameTikett.getDataTiket();
        frameTikett.getNama();
        
        // Tampilkan frame B
        frameTikett.setVisible(true);
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String search = txtCari.getText();
        DefaultTableModel model = (DefaultTableModel) tblPendaftaran.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblPendaftaran.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblPendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendaftaranMouseClicked
        // TODO add your handling code here:
        databaru=false;
        int selectedRowIndex = tblPendaftaran.getSelectedRow();
        if (selectedRowIndex >= 0) {
            databaru = false; // menampilkan data ke textboxt
            DefaultTableModel model = (DefaultTableModel) tblPendaftaran.getModel();
            int selectedRowModelIndex = tblPendaftaran.convertRowIndexToModel(selectedRowIndex);
            String id = model.getValueAt(selectedRowModelIndex, 0).toString();
            String nama = model.getValueAt(selectedRowModelIndex, 1).toString();
            String notelp = model.getValueAt(selectedRowModelIndex, 2).toString();
            String email = model.getValueAt(selectedRowModelIndex, 3).toString();
            String strTanggal = model.getValueAt(selectedRowModelIndex, 4).toString();

            txtId.setText(id);
            txtNama.setText(nama);
            txtPhone.setText(notelp);
            txtEmail.setText(email);

            // Mengubah String tanggal menjadi objek Date
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date tanggalDate = null;
            try {
                tanggalDate = format.parse(strTanggal);
            } catch (ParseException ex) {}

            txtDate.setDate(tanggalDate);
        }
    }//GEN-LAST:event_tblPendaftaranMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        // sembunyikan frame pendaftaram
        this.setVisible(false);

        // Buat instance dari frame Event
        FrameEventt frameEventt = new FrameEventt();

        // Tampilkan frame event
        frameEventt.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePendaftarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePendaftarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePendaftarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePendaftarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePendaftarann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendaftaran;
    private javax.swing.JTextField txtCari;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEvent;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
